import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { trpc } from "../utils/trpc";
import { useSession, signIn, signOut } from "next-auth/react";

const Home: NextPage = () => {
  // const current = trpc.useQuery(["spotify.getCurrentTrack"]);
  const { data: session } = useSession();
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Radiofy</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-screen min-h-screen flex flex-col justify-center items-center p-4 overflow-y-scroll">
        {session ? (
          <>
            <button onClick={() => router.push(`/stations/1234`)}>
              Go to station
            </button>
          </>
        ) : (
          <>
            {" "}
            Not signed in <br />{" "}
            <button onClick={() => signIn()}>Sign in</button>{" "}
          </>
        )}
      </div>
    </>
  );
};

export default Home;
