import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { trpc } from "../utils/trpc";
import { useSession, signIn, signOut } from "next-auth/react";
import Station from "../components/Station";

const Home: NextPage = () => {
  const { data: devices } = trpc.useQuery(["spotify.getDevices"]);
  const { data: myStations } = trpc.useQuery(["dashboard.getOwned"]);
  // const { data: stations } = trpc.useQuery(["stations.getRecent"]);
  const { data: session } = useSession();
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Radiofy</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-screen min-h-screen flex flex-col justify-center items-center p-4 overflow-y-scroll">
        {session ? (
          <div className="flex gap-10">
            {myStations?.map((station) => (
              <Station station={station} />
            ))}
          </div>
        ) : (
          <>
            {" "}
            Not signed in <br />{" "}
            <button onClick={() => signIn()}>Sign in</button>{" "}
          </>
        )}
      </div>
    </>
  );
};

export default Home;
